---
# Continuous testing using the github actions
#

name: CI

# yamllint disable-line rule:truthy
on:
    push:
    schedule:
        - cron: '0 0 1 * *'

jobs:
    lint:
        name: make lint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                sudo apt update
                sudo apt install python3-venv flake8 yamllint
            - name: Run tests
              run: make lint

    test:
        name: make test and coverage report
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                sudo apt update
                sudo apt install python3-venv python3-pytest
            - name: Run tests
              run: make cover

            - name: Upload coverage report
              uses: actions/upload-artifact@v2
              with:
                name: htmlcov
                path: htmlcov
